Module5 task1
htmlacademy-javascript/2131065-kekstagram-26 pull request #6
Opened 2022-06-28 06:08 UTC by n0izzzz

2022-06-28 12:52 UTC, maks88sgt requested changes

2022-06-28 12:52 UTC, maks88sgt commented on js/data.js
> +  for (let i = 0; i < createPhotoObjects.length; i++) {
При таких изменениях тебе нужно будет делать что-то  типа createPhotoObjects().length. Обрати внимание, что у тебя здесь теперь функция, у которой нет длины

2022-06-28 14:31 UTC, n0izzzz commented on js/data.js
> +  for (let i = 0; i < createPhotoObjects.length; i++) {
Обернул все в функцию `collectPhotoDataObjects` и экспортирую ее. Похоже теперь подстановка id работает корректно. 
![image](https://user-images.githubusercontent.com/106422902/176204997-35701a33-50cf-4b92-9f60-b87485b17d30.png)

2022-06-29 12:25 UTC, maks88sgt approved these changes

2022-06-29 12:25 UTC, merged