Отрисуй меня полностью (часть 2)
htmlacademy-javascript/2131065-kekstagram-26 pull request #8
Opened 2022-07-09 11:50 UTC by n0izzzz

Максим, привет!
Посмотри пожалуйста мой вопрос в комментарии на 53 строке в файле js/big-picture.js.

2022-07-09 11:53 UTC, n0izzzz commented on js/big-picture.js
> +      drawComments(); //Спорный момент - стоит ли сначала объявлять, а тут вызывать функцию? Мне кажется что так экономнее с точки зрения ресурсов, но я не уверен.
```suggestion
      drawComments(); //Спорный момент - стоит ли сначала объявлять, а тут вызывать функцию? Мне кажется что так экономнее с точки зрения ресурсов, но я не уверен.
```

2022-07-09 11:53 UTC, n0izzzz commented on js/big-picture.js
> +      drawComments(); //Спорный момент - стоит ли сначала объявлять, а тут вызывать функцию? Мне кажется что так экономнее с точки зрения ресурсов, но я не уверен.
й

2022-07-09 11:54 UTC, n0izzzz commented on js/big-picture.js
> +      drawComments(); //Спорный момент - стоит ли сначала объявлять, а тут вызывать функцию? Мне кажется что так экономнее с точки зрения ресурсов, но я не уверен.
Спорный момент - стоит ли сначала объявлять, а тут вызывать функцию? Мне кажется что так экономнее с точки зрения ресурсов, но я не уверен.

2022-07-11 06:06 UTC, maks88sgt requested changes

2022-07-11 06:06 UTC, maks88sgt commented on js/big-picture.js
> +      drawComments(); //Спорный момент - стоит ли сначала объявлять, а тут вызывать функцию? Мне кажется что так экономнее с точки зрения ресурсов, но я не уверен.
Смотри в целом это ок, но эта функция - это то что можно улучшить. Во-первых с точки зрения организации кода лучше было бы вынести этот метод в отдельный модуль, т.к. он имеет свой самостоятельный функционал. Во-вторых попробуй сделать эту функцию чистой, т.е. зависящей только от входных параметров и возвращающей результат. Такой подход упрощает тестирование, повышает читабельность кода и т.д.

2022-07-14 06:14 UTC, maks88sgt approved these changes

2022-07-14 06:14 UTC, merged